### ISSUE TITLE
Warnung zu fehlendem Health Check

### ISSUE THREAD

**Issue by bliemli** [appuio/techlab#15]
OpenShift zeigt die Warnung an, dass zu Containern keine Health Checks existieren. Erwähnen, dass diese Warnung getrost ignoriert werden kann.

**Comment by dtschan** [comment]
Die Warnung kann nicht einfach ignoriert werden. Am besten würde man im Lab zeigen wie man rudimentäre Health Checks hinzufügt.

**Comment by kallies** [comment]
Es kann sich ja durchaus um einen simplen Healthcheck wie bei [ausnimbus/docker-wordpress](https://github.com/ausnimbus/docker-wordpress/blob/8b80ae0a4987317069ae3b0660c796506b39d47e/s2i/bin/assemble#L43) handeln.
