### ISSUE TITLE
bash completion auf macOS

### ISSUE THREAD

**Issue by bliemli** [appuio/techlab#16]
Der Befehl für die bash completion funktioniert auf macOS nicht.

**Comment by bliemli** [comment]
Mögliche Lösung unter https://www.mankier.com/1/oc-completion.

**Comment by arska** [comment]
1. mkdir ~/bin
1. wget -O ~/bin/oc https://console.appuio.ch/console/extensions/clients/macosx/oc
1. chmod +x ~/bin/oc
1. echo "~/bin/oc completion bash > ~/bin/oc.bashcompletion; source ~/bin/oc.bashcompletion\n" >> ~/.bash_profile

falls noch gar keine bash_completion installiert ist:
1.  brew install bash-completion
1. source $(brew --prefix)/etc/bash_completion
