### ISSUE TITLE
[Feature Request] Upgrade to Openshift/OKD 4.x

### ISSUE THREAD

**Issue by lhoss** [appuio/techlab#51]
Yeah I know, OKD 4.x has not even been released (only a 1. preview 2month ago)
Waiting for that, by tracking https://github.com/openshift/origin/issues/23188

**Comment by bliemli** [comment]
We're currently working on the labs for OpenShift Container Platform 4. These will be applicable to OKD 4.

**Comment by bliemli** [comment]
Updated, see branch lab-4.2.
